# Generated by Django 4.1.2 on 2023-11-04 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filled_image', models.ImageField(upload_to='', verbose_name='filled cart image')),
                ('profile', models.IntegerField()),
                ('created_date', models.DateTimeField(verbose_name='cart created-on date')),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name="good's name")),
                ('about', models.TextField(blank=True, verbose_name='about good')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name="good's image")),
                ('price', models.FloatField(verbose_name="good's price")),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='tag')),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name="good's name")),
                ('about', models.TextField(blank=True, verbose_name='about good')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name="good's image")),
                ('price', models.FloatField(verbose_name="good's price")),
                ('latina_name', models.CharField(max_length=300, verbose_name='latina name')),
                ('tag', models.ManyToManyField(blank=True, to='shop.tag', verbose_name="good's tags")),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ordered_good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.cart', verbose_name='order cart')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.good', verbose_name='oredered good')),
            ],
        ),
        migrations.AddField(
            model_name='good',
            name='tag',
            field=models.ManyToManyField(blank=True, to='shop.tag', verbose_name="good's tags"),
        ),
    ]
