# Generated by Django 4.1.2 on 2023-11-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='price',
            field=models.FloatField(verbose_name="good's price in USD"),
        ),
        migrations.AlterField(
            model_name='plant',
            name='price',
            field=models.FloatField(verbose_name="good's price in USD"),
        ),
    ]
